// AUTO-GENERATED - DO NOT EDIT
// Generated by version-manager.cjs
export const VERSION = '1.0.0';
export const VERSION_NAME = 'TravianAssistant';
export const BUILD_DATE = '2025-08-29T19:31:49.201Z';
export const BUILD_NUMBER = 1756495909201;
