// AUTO-GENERATED - DO NOT EDIT
// Generated by version-manager.cjs
export const VERSION = '1.0.4';
export const VERSION_NAME = 'TravianAssistant';
export const BUILD_DATE = '2025-09-01T01:08:05.808Z';
export const BUILD_NUMBER = 1756688885808;
